using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StarWarsLegionCompanion.Api.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StarWarsLegionCompanion.Api.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class ChosenUpgradeController : ControllerBase
    {

        private readonly DataContext context;

        public ChosenUpgradeController(DataContext context)
        {
            this.context = context;
        }

        /// <summary>
        /// Get the full List of Chosen Upgrades
        /// </summary>
        /// <remarks>
        /// Useful method during development
        /// </remarks>
        /// <returns>The the full list of Chosen Upgrades in the Database</returns>
        [HttpGet]
        public IActionResult GetAllChosenUpgrades()
        {
            var chosenUpgrades = context.ChosenUpgrades.ToList();

            return Ok(chosenUpgrades);
        }
        /// <summary>
        /// Get a chosen Upgrade from its Id
        /// </summary>
        /// <param name="id"></param>
        /// <returns>The Chosen Upgrade object with the Id specified by the parameter</returns>
        [HttpGet("{id}")]
        public IActionResult GetChosenUpgradeById(int id)
        {
            var chosenUpgrade = context.ChosenUpgrades.FirstOrDefault(x => x.Id == id);

            return Ok(chosenUpgrade);
        }
        [HttpGet("ChosenUnit/{id}")]
        public IActionResult GetChosenUpgradeByChosenUnit(int id) //ChosenUnit Id
        {
            var chosenUpgrade = context.ChosenUpgrades.Where(x => x.ChosenUnitId == id);

            return Ok(chosenUpgrade);
        }

        /// <summary>
        /// Post new Chosen Upgrade object to database in Json Format
        /// </summary>
        /// <remarks>
        /// Example:
        ///     {
        ///         "id": 1, *Optional, will be autogenerated*
        ///         "armyid": 1, //reference to armylist by id
        ///         "upgradeid": 1, //reference to Upgrade by id
        ///     }
        ///     
        /// </remarks>
        /// <param name="chosenUpgrade"></param>
        /// <returns>The Newly created object as Json</returns>
        [HttpPost]
        public IActionResult PostChosenUpgrade([FromBody] ChosenUpgrade chosenUpgrade)
        {
            context.ChosenUpgrades.Add(chosenUpgrade);
            context.SaveChanges();
            return CreatedAtAction("GetChosenUpgradeById", new { id = chosenUpgrade.Id }, chosenUpgrade);
        }

        [HttpDelete("{id}")]
        public ActionResult<ChosenUpgrade> DeleteChosenUpgrade(int id)
        {
            var upgrade = context.ChosenUpgrades.Find(id);
            if (upgrade == null)
                return NotFound();
            context.ChosenUpgrades.Remove(upgrade);
            context.SaveChanges();
            return upgrade;
        }
    }
}
