// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWarsLegionCompanion.Api.Models;

namespace StarWarsLegionCompanion.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210131201853_updateChosenUnit")]
    partial class updateChosenUnit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AttackDieWeapon", b =>
                {
                    b.Property<int>("AttackDieId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponsId")
                        .HasColumnType("int");

                    b.HasKey("AttackDieId", "WeaponsId");

                    b.HasIndex("WeaponsId");

                    b.ToTable("AttackDieWeapon");

                    b.HasData(
                        new
                        {
                            AttackDieId = 16,
                            WeaponsId = 1
                        },
                        new
                        {
                            AttackDieId = 22,
                            WeaponsId = 2
                        },
                        new
                        {
                            AttackDieId = 26,
                            WeaponsId = 3
                        });
                });

            modelBuilder.Entity("KeywordUnit", b =>
                {
                    b.Property<int>("KeywordsId")
                        .HasColumnType("int");

                    b.Property<int>("UnitsId")
                        .HasColumnType("int");

                    b.HasKey("KeywordsId", "UnitsId");

                    b.HasIndex("UnitsId");

                    b.ToTable("KeywordUnit");

                    b.HasData(
                        new
                        {
                            KeywordsId = 1,
                            UnitsId = 1
                        },
                        new
                        {
                            KeywordsId = 2,
                            UnitsId = 1
                        },
                        new
                        {
                            KeywordsId = 3,
                            UnitsId = 1
                        },
                        new
                        {
                            KeywordsId = 4,
                            UnitsId = 1
                        },
                        new
                        {
                            KeywordsId = 3,
                            UnitsId = 50
                        },
                        new
                        {
                            KeywordsId = 4,
                            UnitsId = 50
                        });
                });

            modelBuilder.Entity("KeywordUpgrade", b =>
                {
                    b.Property<int>("KeywordsId")
                        .HasColumnType("int");

                    b.Property<int>("UpgradesId")
                        .HasColumnType("int");

                    b.HasKey("KeywordsId", "UpgradesId");

                    b.HasIndex("UpgradesId");

                    b.ToTable("KeywordUpgrade");

                    b.HasData(
                        new
                        {
                            KeywordsId = 7,
                            UpgradesId = 4
                        });
                });

            modelBuilder.Entity("KeywordWeapon", b =>
                {
                    b.Property<int>("KeywordsId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponsId")
                        .HasColumnType("int");

                    b.HasKey("KeywordsId", "WeaponsId");

                    b.HasIndex("WeaponsId");

                    b.ToTable("KeywordWeapon");

                    b.HasData(
                        new
                        {
                            KeywordsId = 6,
                            WeaponsId = 1
                        },
                        new
                        {
                            KeywordsId = 5,
                            WeaponsId = 1
                        },
                        new
                        {
                            KeywordsId = 6,
                            WeaponsId = 2
                        },
                        new
                        {
                            KeywordsId = 8,
                            WeaponsId = 3
                        },
                        new
                        {
                            KeywordsId = 9,
                            WeaponsId = 3
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.Army", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PointLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ArmyLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FactionId = 1,
                            Name = "Holy Molys",
                            PlayerId = 1,
                            PointLimit = 800
                        },
                        new
                        {
                            Id = 2,
                            FactionId = 2,
                            Name = "City Bois",
                            PlayerId = 2,
                            PointLimit = 800
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.AttackDie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AttackDie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "White",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "White",
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "White",
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "White",
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "White",
                            Value = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "White",
                            Value = 6
                        },
                        new
                        {
                            Id = 11,
                            Name = "Black",
                            Value = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Black",
                            Value = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Black",
                            Value = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Black",
                            Value = 4
                        },
                        new
                        {
                            Id = 15,
                            Name = "Black",
                            Value = 5
                        },
                        new
                        {
                            Id = 16,
                            Name = "Black",
                            Value = 6
                        },
                        new
                        {
                            Id = 21,
                            Name = "Red",
                            Value = 1
                        },
                        new
                        {
                            Id = 22,
                            Name = "Red",
                            Value = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "Red",
                            Value = 3
                        },
                        new
                        {
                            Id = 24,
                            Name = "Red",
                            Value = 4
                        },
                        new
                        {
                            Id = 25,
                            Name = "Red",
                            Value = 5
                        },
                        new
                        {
                            Id = 26,
                            Name = "Red",
                            Value = 6
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.AttackSurge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AttackSurges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hit"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Critical"
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.ChosenUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ArmyId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("UnitRankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChosenUnits");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            ArmyId = 1,
                            UnitId = 1,
                            UnitRankId = 1
                        },
                        new
                        {
                            Id = 11,
                            ArmyId = 1,
                            UnitId = 3,
                            UnitRankId = 3
                        },
                        new
                        {
                            Id = 12,
                            ArmyId = 1,
                            UnitId = 3,
                            UnitRankId = 3
                        },
                        new
                        {
                            Id = 13,
                            ArmyId = 2,
                            UnitId = 50,
                            UnitRankId = 1
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.ChosenUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ChosenUnitId")
                        .HasColumnType("int");

                    b.Property<int>("UpgradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChosenUpgrades");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            ChosenUnitId = 10,
                            UpgradeId = 1
                        },
                        new
                        {
                            Id = 21,
                            ChosenUnitId = 10,
                            UpgradeId = 3
                        },
                        new
                        {
                            Id = 22,
                            ChosenUnitId = 11,
                            UpgradeId = 4
                        },
                        new
                        {
                            Id = 24,
                            ChosenUnitId = 13,
                            UpgradeId = 2
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Factions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rebel Alliance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Galactic Empire"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Separatist Alliance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Galactic Republic"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Neutral"
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AbilityValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsCardAction")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreeAction")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Keywords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbilityValue = 1,
                            IsCardAction = true,
                            IsFreeAction = false,
                            Name = "Jump",
                            Text = "Perform a move during which you ignore terrain that is height 1 or lower. This is treated as a move action."
                        },
                        new
                        {
                            Id = 2,
                            IsCardAction = false,
                            IsFreeAction = false,
                            Name = "Charge",
                            Text = "After you perform a move action, you may perform a free melee attack action."
                        },
                        new
                        {
                            Id = 3,
                            IsCardAction = false,
                            IsFreeAction = false,
                            Name = "Deflect",
                            Text = "After While defending, if you spend a dodge token, you gain “Surge: Block”: if it’s a ranged attack, the attacker suffers 1 wound for each Surge rolled."
                        },
                        new
                        {
                            Id = 4,
                            IsCardAction = false,
                            IsFreeAction = false,
                            Name = "Immune: Pierce",
                            Text = "Pierce cannot be used against you."
                        },
                        new
                        {
                            Id = 5,
                            AbilityValue = 2,
                            IsCardAction = false,
                            IsFreeAction = false,
                            Name = "Impact",
                            Text = "While attacking a unit that has Armor, change up to X Dice Hit.png result(s) to Dice Crit.png result(s)."
                        },
                        new
                        {
                            Id = 6,
                            AbilityValue = 2,
                            IsCardAction = false,
                            IsFreeAction = false,
                            Name = "Pierce",
                            Text = "When attacking, ignore up to 2 block results."
                        },
                        new
                        {
                            Id = 7,
                            AbilityValue = 1,
                            IsCardAction = false,
                            IsFreeAction = false,
                            Name = "Precise 1",
                            Text = "When you spend an aim token, reroll up to 1 additional die."
                        },
                        new
                        {
                            Id = 8,
                            AbilityValue = 3,
                            IsCardAction = false,
                            IsFreeAction = false,
                            Name = "Impact",
                            Text = "While attacking a unit that has Armor, change up to X Dice Hit.png result(s) to Dice Crit.png result(s)."
                        },
                        new
                        {
                            Id = 9,
                            AbilityValue = 3,
                            IsCardAction = false,
                            IsFreeAction = false,
                            Name = "Pierce",
                            Text = "When attacking, ignore up to 2 block results."
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Henrik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kenneth"
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.RangeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RangeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Melee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ranged"
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Commander"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Operative"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Corps"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Special Forces"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Support"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Heavy"
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ArmyId")
                        .HasColumnType("int");

                    b.Property<int>("AttackSurgeId")
                        .HasColumnType("int");

                    b.Property<int>("Courage")
                        .HasColumnType("int");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefenseRed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefenseSurge")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("bit");

                    b.Property<int>("MinisInUnit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointCost")
                        .HasColumnType("int");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WoundThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackSurgeId = 3,
                            Courage = 3,
                            FactionId = 1,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Luke Skywalker",
                            PointCost = 160,
                            RankId = 1,
                            Speed = 2,
                            SurName = "HERO OF THE REBELLION",
                            UnitTypeId = 1,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 2,
                            AttackSurgeId = 3,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Leia Organa",
                            PointCost = 90,
                            RankId = 1,
                            Speed = 2,
                            SurName = "FEARLESS AND INVENTIVE",
                            UnitTypeId = 1,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 3,
                            AttackSurgeId = 1,
                            Courage = 1,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Rebel Troopers",
                            PointCost = 40,
                            RankId = 3,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 4,
                            AttackSurgeId = 2,
                            Courage = 1,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Fleet Troopers",
                            PointCost = 44,
                            RankId = 3,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 5,
                            AttackSurgeId = 3,
                            Courage = 5,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "T-47 Airspeeder",
                            PointCost = 175,
                            RankId = 6,
                            Speed = 3,
                            UnitTypeId = 2,
                            WoundThreshold = 7
                        },
                        new
                        {
                            Id = 6,
                            AttackSurgeId = 3,
                            Courage = 4,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "AT-RT",
                            PointCost = 55,
                            RankId = 5,
                            Speed = 2,
                            UnitTypeId = 3,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 7,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Rebel Commandos",
                            PointCost = 60,
                            RankId = 4,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 8,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "Rebel Commandos",
                            PointCost = 16,
                            RankId = 4,
                            Speed = 2,
                            SurName = "Strike Team",
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 9,
                            AttackSurgeId = 3,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Han Solo",
                            PointCost = 120,
                            RankId = 1,
                            Speed = 2,
                            SurName = "Unorthodox general",
                            UnitTypeId = 1,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 10,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "1.4 FD Laser Cannon Team",
                            PointCost = 70,
                            RankId = 5,
                            Speed = 0,
                            UnitTypeId = 4,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 11,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "Rebel Officer",
                            PointCost = 50,
                            RankId = 1,
                            Speed = 2,
                            SurName = "Resolute Commander",
                            UnitTypeId = 1,
                            WoundThreshold = 4
                        },
                        new
                        {
                            Id = 12,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 3,
                            Name = "Wookie Warriors",
                            PointCost = 75,
                            RankId = 4,
                            Speed = 2,
                            UnitTypeId = 6,
                            WoundThreshold = 3
                        },
                        new
                        {
                            Id = 13,
                            AttackSurgeId = 3,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = false,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Chewbacca",
                            PointCost = 110,
                            RankId = 2,
                            Speed = 2,
                            SurName = "walking Carpet",
                            UnitTypeId = 6,
                            WoundThreshold = 9
                        },
                        new
                        {
                            Id = 14,
                            AttackSurgeId = 3,
                            Courage = 3,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Jyn Erso",
                            PointCost = 130,
                            RankId = 1,
                            Speed = 2,
                            SurName = "Stardust",
                            UnitTypeId = 1,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 15,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Rebel Pathfinders",
                            PointCost = 68,
                            RankId = 4,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 16,
                            AttackSurgeId = 2,
                            Courage = 4,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "X-34 Landspeeder",
                            PointCost = 75,
                            RankId = 6,
                            Speed = 2,
                            UnitTypeId = 2,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 17,
                            AttackSurgeId = 3,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = true,
                            IsDefenseSurge = true,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Sabine Wren",
                            PointCost = 125,
                            RankId = 2,
                            Speed = 3,
                            SurName = "Explosive Artist",
                            UnitTypeId = 1,
                            WoundThreshold = 5
                        },
                        new
                        {
                            Id = 18,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 2,
                            Name = "Tauntaun Riders",
                            PointCost = 90,
                            RankId = 5,
                            Speed = 3,
                            UnitTypeId = 5,
                            WoundThreshold = 4
                        },
                        new
                        {
                            Id = 19,
                            AttackSurgeId = 2,
                            Courage = 1,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Rebel Veterans",
                            PointCost = 44,
                            RankId = 3,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 20,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "Mark II Medium Blaster Trooper",
                            PointCost = 38,
                            RankId = 3,
                            Speed = 1,
                            UnitTypeId = 4,
                            WoundThreshold = 4
                        },
                        new
                        {
                            Id = 21,
                            AttackSurgeId = 3,
                            Courage = 4,
                            FactionId = 1,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Luke Skywalker",
                            PointCost = 200,
                            RankId = 2,
                            Speed = 2,
                            SurName = "Jedi Knight",
                            UnitTypeId = 1,
                            WoundThreshold = 7
                        },
                        new
                        {
                            Id = 22,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = false,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "R2-D2",
                            PointCost = 35,
                            RankId = 2,
                            Speed = 1,
                            SurName = "Hero of Thousands Devices",
                            UnitTypeId = 7,
                            WoundThreshold = 4
                        },
                        new
                        {
                            Id = 23,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Casisian Andor",
                            PointCost = 90,
                            RankId = 1,
                            Speed = 2,
                            SurName = "Capable Intelligence Agent",
                            UnitTypeId = 1,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 24,
                            AttackSurgeId = 3,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "K-2SO",
                            PointCost = 70,
                            RankId = 2,
                            Speed = 1,
                            SurName = "Sardonic Security Droid",
                            UnitTypeId = 7,
                            WoundThreshold = 5
                        },
                        new
                        {
                            Id = 25,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = true,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 3,
                            Name = "Mandalorian Resistance",
                            PointCost = 72,
                            RankId = 4,
                            Speed = 3,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 26,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = true,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "Mandalorian Resistance",
                            PointCost = 34,
                            RankId = 4,
                            Speed = 3,
                            SurName = "Clan Wren",
                            UnitTypeId = 1,
                            WoundThreshold = 2
                        },
                        new
                        {
                            Id = 27,
                            AttackSurgeId = 3,
                            Courage = 2,
                            FactionId = 1,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Lando Calrissian",
                            PointCost = 105,
                            RankId = 1,
                            Speed = 2,
                            SurName = "Smooth Operator",
                            UnitTypeId = 1,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 50,
                            AttackSurgeId = 1,
                            Courage = 0,
                            FactionId = 2,
                            IsDefenseRed = false,
                            IsDefenseSurge = false,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Darth Vader",
                            PointCost = 200,
                            RankId = 1,
                            Speed = 1,
                            SurName = "DARK LORD OF THE SITH",
                            UnitTypeId = 1,
                            WoundThreshold = 8
                        },
                        new
                        {
                            Id = 51,
                            AttackSurgeId = 2,
                            Courage = 1,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Storm Trooper",
                            PointCost = 44,
                            RankId = 3,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 52,
                            AttackSurgeId = 3,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "General Veers",
                            PointCost = 80,
                            RankId = 1,
                            Speed = 2,
                            SurName = "Master Tactician",
                            UnitTypeId = 1,
                            WoundThreshold = 5
                        },
                        new
                        {
                            Id = 53,
                            AttackSurgeId = 1,
                            Courage = 8,
                            FactionId = 2,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "AT-ST",
                            PointCost = 195,
                            RankId = 6,
                            Speed = 2,
                            UnitTypeId = 3,
                            WoundThreshold = 11
                        },
                        new
                        {
                            Id = 54,
                            AttackSurgeId = 2,
                            Courage = 0,
                            FactionId = 2,
                            IsDefenseRed = false,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 2,
                            Name = "74-Z Speeder Bikes",
                            PointCost = 90,
                            RankId = 5,
                            Speed = 3,
                            UnitTypeId = 2,
                            WoundThreshold = 3
                        },
                        new
                        {
                            Id = 55,
                            AttackSurgeId = 3,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "E-Web Heavy Blaster Team",
                            PointCost = 55,
                            RankId = 5,
                            Speed = 1,
                            UnitTypeId = 4,
                            WoundThreshold = 4
                        },
                        new
                        {
                            Id = 56,
                            AttackSurgeId = 1,
                            Courage = 1,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Imperial Royal Guards",
                            PointCost = 44,
                            RankId = 3,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 57,
                            AttackSurgeId = 1,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "Scout Trooper",
                            PointCost = 16,
                            RankId = 4,
                            Speed = 2,
                            SurName = "Strike Team",
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 58,
                            AttackSurgeId = 1,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Scout Trooper",
                            PointCost = 60,
                            RankId = 4,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 59,
                            AttackSurgeId = 3,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Director Orson Krennic",
                            PointCost = 90,
                            RankId = 1,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 60,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Imperial Death Trooper",
                            PointCost = 76,
                            RankId = 3,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 61,
                            AttackSurgeId = 3,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = false,
                            IsDefenseSurge = false,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Bossk",
                            PointCost = 115,
                            RankId = 2,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 7
                        },
                        new
                        {
                            Id = 62,
                            AttackSurgeId = 3,
                            Courage = 4,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = true,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Emperor Palpatine",
                            PointCost = 210,
                            RankId = 1,
                            Speed = 1,
                            SurName = "Ruler of The Galactic Empire",
                            UnitTypeId = 1,
                            WoundThreshold = 5
                        },
                        new
                        {
                            Id = 74,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = false,
                            IsDefenseSurge = true,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "Imperial Officer",
                            PointCost = 50,
                            RankId = 1,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 4
                        },
                        new
                        {
                            Id = 63,
                            AttackSurgeId = 2,
                            Courage = 1,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Snowtrooper",
                            PointCost = 48,
                            RankId = 3,
                            Speed = 1,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 64,
                            AttackSurgeId = 1,
                            Courage = 6,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "TX-225 GAVw Occupier Combat Assault Tank",
                            PointCost = 155,
                            RankId = 6,
                            Speed = 1,
                            UnitTypeId = 3,
                            WoundThreshold = 8
                        },
                        new
                        {
                            Id = 65,
                            AttackSurgeId = 1,
                            Courage = 1,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Shoretrooper",
                            PointCost = 52,
                            RankId = 3,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 66,
                            AttackSurgeId = 2,
                            Courage = 3,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "Iden Versio",
                            PointCost = 100,
                            RankId = 1,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 67,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "Dewback Rider",
                            PointCost = 90,
                            RankId = 5,
                            Speed = 1,
                            UnitTypeId = 5,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 68,
                            AttackSurgeId = 1,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "DF-90 Mortar Trooper",
                            PointCost = 36,
                            RankId = 3,
                            Speed = 1,
                            UnitTypeId = 4,
                            WoundThreshold = 3
                        },
                        new
                        {
                            Id = 69,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 4,
                            Name = "Imperial Special Forces",
                            PointCost = 68,
                            RankId = 3,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 1
                        },
                        new
                        {
                            Id = 70,
                            AttackSurgeId = 2,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = false,
                            MinisInUnit = 1,
                            Name = "Imperial Special Forces",
                            PointCost = 34,
                            RankId = 3,
                            Speed = 2,
                            SurName = "Inferno Squad",
                            UnitTypeId = 1,
                            WoundThreshold = 2
                        },
                        new
                        {
                            Id = 71,
                            AttackSurgeId = 3,
                            Courage = 3,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = true,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Boba Fett",
                            PointCost = 140,
                            RankId = 2,
                            Speed = 3,
                            SurName = "Infamous Bounty Hunter",
                            UnitTypeId = 1,
                            WoundThreshold = 5
                        },
                        new
                        {
                            Id = 72,
                            AttackSurgeId = 1,
                            Courage = 3,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Darth Vader",
                            PointCost = 170,
                            RankId = 2,
                            Speed = 1,
                            SurName = "The Emperor's Apprentice",
                            UnitTypeId = 1,
                            WoundThreshold = 6
                        },
                        new
                        {
                            Id = 73,
                            AttackSurgeId = 3,
                            Courage = 2,
                            FactionId = 2,
                            IsDefenseRed = true,
                            IsDefenseSurge = false,
                            IsUnique = true,
                            MinisInUnit = 1,
                            Name = "Agent Kallus",
                            PointCost = 90,
                            RankId = 1,
                            Speed = 2,
                            UnitTypeId = 1,
                            WoundThreshold = 6
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.UnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Trooper"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Repulsor Vehicle"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ground Vehicle"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Emplacement Trooper"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Creature Tropper"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Wookie Tropper"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Droid Trooper"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Clone Trooper"
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.Upgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsExhaustable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreeAction")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointCost")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpgradeCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.Property<int?>("WoundThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Upgrades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsExhaustable = true,
                            IsFreeAction = true,
                            Name = "Force Push",
                            PointCost = 10,
                            Text = "Choose an enemy trooper unit at range 1. Perform a speed-1 move with that unit, even if it is engaged.",
                            UpgradeCategoryId = 5,
                            WeaponId = 0
                        },
                        new
                        {
                            Id = 2,
                            IsExhaustable = true,
                            IsFreeAction = true,
                            Name = "Force Choke",
                            PointCost = 5,
                            Text = "Choose a non-commander, non-operative enemy trooper mini at range 1. It suffers 1 wound.",
                            UpgradeCategoryId = 5,
                            WeaponId = 0
                        },
                        new
                        {
                            Id = 3,
                            IsExhaustable = false,
                            IsFreeAction = false,
                            Name = "Battle Meditation",
                            PointCost = 10,
                            Text = "While you are issuing orders using a command card, you may issue 1 of those orders to any friendly unit on the battlefield, instead of a unit indicated on the command card.",
                            UpgradeCategoryId = 5,
                            WeaponId = 0
                        },
                        new
                        {
                            Id = 4,
                            IsExhaustable = false,
                            IsFreeAction = false,
                            Name = "Targeting Scopes",
                            PointCost = 6,
                            Text = "You gain Precise 1",
                            UpgradeCategoryId = 6,
                            WeaponId = 0
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.UpgradeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpgradeId")
                        .HasColumnType("int");

                    b.Property<int?>("UpgradeId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpgradeId1");

                    b.ToTable("UpgradeCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Armament",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Command",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comms",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Crew",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Force",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gear",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Generator",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Grenades",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hardpoint",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 10,
                            Name = "Heavy Weapon",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ordnance",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 12,
                            Name = "Personnel",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pilot",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 14,
                            Name = "Training",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 15,
                            Name = "Armament",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 16,
                            Name = "Command",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 17,
                            Name = "Comms",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 18,
                            Name = "Crew",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 19,
                            Name = "Force",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 20,
                            Name = "Gear",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 21,
                            Name = "Generator",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 22,
                            Name = "Grenades",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 23,
                            Name = "Hardpoint",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 24,
                            Name = "Heavy Weapon",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 25,
                            Name = "Ordnance",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 26,
                            Name = "Personnel",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 27,
                            Name = "Pilot",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 28,
                            Name = "Training",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 29,
                            Name = "Armament",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 30,
                            Name = "Command",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 31,
                            Name = "Comms",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 32,
                            Name = "Crew",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 33,
                            Name = "Force",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 34,
                            Name = "Gear",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 35,
                            Name = "Generator",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 36,
                            Name = "Grenades",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 37,
                            Name = "Hardpoint",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 38,
                            Name = "Heavy Weapon",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 39,
                            Name = "Ordnance",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 40,
                            Name = "Personnel",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 41,
                            Name = "Pilot",
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 42,
                            Name = "Training",
                            UpgradeId = 0
                        });
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("MaxRange")
                        .HasColumnType("int");

                    b.Property<int?>("MinRange")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RangeTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UpgradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anakin's Lightsaber",
                            RangeTypeId = 1,
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 2,
                            MaxRange = 2,
                            MinRange = 1,
                            Name = "Luke's DL-44 Blaster Pistol",
                            RangeTypeId = 2,
                            UpgradeId = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vader's Lightsaber",
                            RangeTypeId = 1,
                            UpgradeId = 0
                        });
                });

            modelBuilder.Entity("UnitUpgradeCategory", b =>
                {
                    b.Property<int>("UnitsId")
                        .HasColumnType("int");

                    b.Property<int>("UpgradeCategoriesId")
                        .HasColumnType("int");

                    b.HasKey("UnitsId", "UpgradeCategoriesId");

                    b.HasIndex("UpgradeCategoriesId");

                    b.ToTable("UnitUpgradeCategory");

                    b.HasData(
                        new
                        {
                            UnitsId = 1,
                            UpgradeCategoriesId = 5
                        },
                        new
                        {
                            UnitsId = 1,
                            UpgradeCategoriesId = 19
                        },
                        new
                        {
                            UnitsId = 1,
                            UpgradeCategoriesId = 6
                        },
                        new
                        {
                            UnitsId = 50,
                            UpgradeCategoriesId = 5
                        },
                        new
                        {
                            UnitsId = 50,
                            UpgradeCategoriesId = 19
                        },
                        new
                        {
                            UnitsId = 50,
                            UpgradeCategoriesId = 33
                        });
                });

            modelBuilder.Entity("UnitWeapon", b =>
                {
                    b.Property<int>("UnitsId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponsId")
                        .HasColumnType("int");

                    b.HasKey("UnitsId", "WeaponsId");

                    b.HasIndex("WeaponsId");

                    b.ToTable("UnitWeapon");

                    b.HasData(
                        new
                        {
                            UnitsId = 1,
                            WeaponsId = 1
                        },
                        new
                        {
                            UnitsId = 1,
                            WeaponsId = 2
                        },
                        new
                        {
                            UnitsId = 50,
                            WeaponsId = 3
                        });
                });

            modelBuilder.Entity("AttackDieWeapon", b =>
                {
                    b.HasOne("StarWarsLegionCompanion.Api.Models.AttackDie", null)
                        .WithMany()
                        .HasForeignKey("AttackDieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsLegionCompanion.Api.Models.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeywordUnit", b =>
                {
                    b.HasOne("StarWarsLegionCompanion.Api.Models.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsLegionCompanion.Api.Models.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeywordUpgrade", b =>
                {
                    b.HasOne("StarWarsLegionCompanion.Api.Models.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsLegionCompanion.Api.Models.Upgrade", null)
                        .WithMany()
                        .HasForeignKey("UpgradesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeywordWeapon", b =>
                {
                    b.HasOne("StarWarsLegionCompanion.Api.Models.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsLegionCompanion.Api.Models.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWarsLegionCompanion.Api.Models.UpgradeCategory", b =>
                {
                    b.HasOne("StarWarsLegionCompanion.Api.Models.Upgrade", "Upgrade")
                        .WithMany()
                        .HasForeignKey("UpgradeId1");

                    b.Navigation("Upgrade");
                });

            modelBuilder.Entity("UnitUpgradeCategory", b =>
                {
                    b.HasOne("StarWarsLegionCompanion.Api.Models.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsLegionCompanion.Api.Models.UpgradeCategory", null)
                        .WithMany()
                        .HasForeignKey("UpgradeCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UnitWeapon", b =>
                {
                    b.HasOne("StarWarsLegionCompanion.Api.Models.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsLegionCompanion.Api.Models.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
